# Generated by Django 6.0.2 on 2026-02-28 22:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatuschoices')),
            ],
        ),
    ]
