# Generated by Django 6.0.2 on 2026-03-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactstatuschoices',
            options={'verbose_name': 'Contact status choice', 'verbose_name_plural': 'Contact status choices'},
        ),
    ]
