# Generated by Django 6.0.2 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time_updated',
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactstatuschoices',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
