# Generated by Django 6.0.2 on 2026-03-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_geocache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geocache',
            old_name='name',
            new_name='city_name',
        ),
    ]
